### ISSUE TITLE
no such file

### ISSUE THREAD

**Issue by LiangHeng121** [enesduran/HMP#3]
Thanks for the project!But there is a problem while running on in_the_wild videos:

Traceback (most recent call last):
  File "/home/heng/miniforge3/envs/hmp/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/heng/miniforge3/envs/hmp/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/heng/下载/HMP-main/external/PyMAF-X/apps/demo_mano.py", line 665, in <module>
    parse_args(args)
  File "/home/heng/下载/HMP-main/external/PyMAF-X/core/cfgs.py", line 80, in parse_args
    cfg = update_cfg(args.cfg_file)
  File "/home/heng/下载/HMP-main/external/PyMAF-X/core/cfgs.py", line 72, in update_cfg
    cfg.merge_from_file(cfg_file)
  File "/home/heng/miniforge3/envs/hmp/lib/python3.10/site-packages/yacs/config.py", line 211, in merge_from_file
    with open(cfg_filename, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/pymafx_config.yaml'
Traceback (most recent call last):
  File "/home/heng/下载/HMP-main/src/fitting_app.py", line 1462, in <module>
    run_opt(opt)
  File "/home/heng/下载/HMP-main/src/fitting_app.py", line 1400, in run_opt
    multi_stage_opt(os.path.join('./configs', opt.config), opt.dataname, init_method)
  File "/home/heng/下载/HMP-main/src/fitting_app.py", line 748, in multi_stage_opt
    init_out_obj = eval(f"run_{init_method_name}")(args.vid_path, init_method_out_path,
  File "/home/heng/下载/HMP-main/src/fitting_utils.py", line 391, in run_pymafx
    out_obj = joblib.load(pickle_path)
  File "/home/heng/miniforge3/envs/hmp/lib/python3.10/site-packages/joblib/numpy_pickle.py", line 650, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/rgb_data/in_the_wild/1/pymafx_out/output.pkl'

why is there no configs/pymafx_config.yaml?

**Comment by enesduran** [comment]
Hey, sorry for the late response, I uploaded pymafx_config.yaml file. Can you try again?
